[package]
name = "git-ls"
version = "1.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.18", features = ["derive"] }
colored = "2.1.0"
dirs = "5.0.1"
git2 = "0.19.0"
regex = "1.11.0"

