[package]
name = "git-ls"
version = "1.1.1"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.35", features = ["derive"] }
colored = "3.0.0"
dirs = "6.0.0"
git2 = "0.20.1"
regex = "1.11.1"
