name: Release

on:
  pull_request:
    types:
      - opened

  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build project
        run: cargo build --release --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Lint with clippy
        run: cargo clippy --all-targets --all-features
      - name: Check formatting
        run: cargo fmt --all --check
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-bin
          path: target/release/git-ls
  release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      discussions: write

    steps:
      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          name: linux-bin
          path: ${{github.workspace}}
      - name: Create a Release
        uses: softprops/action-gh-release@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{github.workspace}}/linux-bin
